import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Languages, Copy, Check, RotateCcw, Zap, ChevronDown, ChevronUp, Search, Share2 } from 'lucide-react'
import { api } from '../utils/api'
import { ScrollReveal } from '../components/AnimatedComponents'
import DemoModeBadge from '../components/DemoModeBadge'
import { useToast } from '../components/Toast'

const DEMO_PRODUCTS = [
  {
    name: 'Premium Basmati Rice 5kg',
    category: 'Groceries',
    features: ['Aged 2 years', 'Extra-long grain', 'Aromatic', 'Pesticide-free', 'From Dehradun valley'],
    specifications: { weight: '5kg', grain_length: '8.4mm', aging: '2 years', origin: 'Dehradun, Uttarakhand' },
  },
  {
    name: 'Handloom Cotton Kurta - Men',
    category: 'Fashion',
    features: ['Pure cotton handloom', 'Chikankari embroidery', 'Comfortable fit', 'Machine washable', 'Available in 5 colors'],
    specifications: { fabric: '100% Cotton', type: 'Chikankari', sizes: 'S, M, L, XL, XXL', origin: 'Lucknow' },
  },
  {
    name: 'Organic Turmeric Powder 500g',
    category: 'Groceries',
    features: ['Organic certified', 'High curcumin 7.5%', 'Lakadong variety', 'Lab tested', 'No artificial color'],
    specifications: { weight: '500g', curcumin: '7.5%', type: 'Lakadong', origin: 'Meghalaya' },
  },
  {
    name: 'Ghee (Pure Desi) 1L',
    category: 'Groceries',
    features: ['A2 cow milk', 'Bilona method', 'Rich aroma', 'No preservatives', 'Grass-fed cows'],
    specifications: { volume: '1 litre', type: 'A2 Bilona', fat: '99.7%', origin: 'Gujarat' },
  },
  {
    name: 'Neem Wood Comb Set',
    category: 'Home & Kitchen',
    features: ['100% Neem wood', 'Anti-dandruff', 'Anti-static', 'Eco-friendly', 'Set of 3 sizes'],
    specifications: { material: 'Neem Wood', pieces: '3', type: 'Wide + Fine + Pocket', origin: 'Rajasthan' },
  },
]

const LANGUAGES = [
  { code: 'en', name: 'English', nameNative: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'Hindi', nameNative: 'हिंदी', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nameNative: 'தமிழ்', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nameNative: 'বাংলা', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nameNative: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nameNative: 'मराठी', flag: '🇮🇳' },
]

export default function ContentPage() {
  const { toast } = useToast()
  const [productName, setProductName] = useState('')
  const [category, setCategory] = useState('Groceries')
  const [features, setFeatures] = useState('')
  const [selectedLangs, setSelectedLangs] = useState<string[]>(['en', 'hi'])
  const [tone, setTone] = useState('persuasive')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState<any>(null)
  const [error, setError] = useState('')
  const [copiedIdx, setCopiedIdx] = useState<number | null>(null)
  const [expandedIdx, setExpandedIdx] = useState<number | null>(0)

  function loadDemo(demo: typeof DEMO_PRODUCTS[0]) {
    setProductName(demo.name)
    setCategory(demo.category)
    setFeatures(demo.features.join(', '))
    setResult(null)
  }

  function toggleLang(code: string) {
    setSelectedLangs(prev =>
      prev.includes(code) ? prev.filter(l => l !== code) : [...prev, code]
    )
  }

  async function handleCopy(text: string, idx: number) {
    await navigator.clipboard.writeText(text)
    setCopiedIdx(idx)
    toast('success', 'Copied to clipboard!')
    setTimeout(() => setCopiedIdx(null), 2000)
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (selectedLangs.length === 0) {
      setError('Select at least one language')
      return
    }
    setLoading(true)
    setError('')
    setResult(null)

    try {
      const data = await api.generateDescription({
        productName,
        category,
        features: features.split(',').map(f => f.trim()).filter(Boolean),
        specifications: {},
        targetLanguages: selectedLangs,
        tone,
      })
      setResult(data)
      setExpandedIdx(0)
      if (data.demoMode) toast('info', 'AI demo mode — smart fallback data')
      else toast('success', `${selectedLangs.length} descriptions generated!`)
    } catch (err: any) {
      setError(err.message || 'Failed to generate descriptions')
      toast('error', 'AI temporarily unavailable. Try again shortly.')
    } finally {
      setLoading(false)
    }
  }

  function shareDescriptionWhatsApp(desc: any) {
    const text = `*${desc.title}*\n\n${desc.description}\n\n${desc.bulletPoints?.map((b: string) => `• ${b}`).join('\n') || ''}\n\nGenerated by BharatBazaar AI`
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank')
  }

  return (
    <div className="p-6 lg:p-8 max-w-[1400px]">
      {/* Page Header */}
      <div className="page-header rounded-2xl mb-6 relative overflow-hidden">
        <div className="absolute inset-0 opacity-20">
          <div className="absolute top-0 left-0 w-64 h-64 bg-teal-400 rounded-full blur-[100px]" />
        </div>
        <div className="relative z-10 flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl bg-white/15 backdrop-blur-sm flex items-center justify-center">
            <Languages className="w-6 h-6 text-teal-300" />
          </div>
          <div>
            <h1 className="font-display text-2xl font-bold">Multilingual Content Generator</h1>
            <p className="text-sm text-white/60">Culturally adapted descriptions — not just translations</p>
          </div>
        </div>
      </div>

      {/* Demo Buttons */}
      <div className="flex flex-wrap gap-2 mb-6">
        <span className="text-sm text-gray-500 py-2">Quick Demo:</span>
        {DEMO_PRODUCTS.map(demo => (
          <motion.button
            key={demo.name}
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={() => loadDemo(demo)}
            className="text-sm px-4 py-2 bg-[#1a1a1d] border border-[#2a2a2d] rounded-xl hover:border-bazaar-300 hover:bg-bazaar-500/10 transition-all shadow-sm shadow-black/20"
          >
            {demo.name}
          </motion.button>
        ))}
      </div>

      <div className="grid lg:grid-cols-5 gap-8">
        {/* Input Form */}
        <form onSubmit={handleSubmit} className="lg:col-span-2 bg-[#1a1a1d] rounded-2xl p-6 shadow-sm shadow-black/20 border border-[#2a2a2d] space-y-4 h-fit">
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-1">Product Name</label>
            <input
              type="text"
              value={productName}
              onChange={e => setProductName(e.target.value)}
              placeholder="e.g., Premium Basmati Rice 5kg"
              className="input-field"
              required
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-1">Category</label>
            <select value={category} onChange={e => setCategory(e.target.value)} className="input-field">
              {['Electronics', 'Fashion', 'Groceries', 'Home & Kitchen', 'Beauty & Personal Care'].map(c => (
                <option key={c} value={c}>{c}</option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-1">Key Features (comma separated)</label>
            <textarea
              value={features}
              onChange={e => setFeatures(e.target.value)}
              placeholder="Aged 2 years, Extra-long grain, Aromatic..."
              className="input-field min-h-[80px] resize-y"
              required
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-1">Tone</label>
            <select value={tone} onChange={e => setTone(e.target.value)} className="input-field">
              <option value="persuasive">Persuasive (Marketing)</option>
              <option value="formal">Formal (Professional)</option>
              <option value="casual">Casual (Friendly)</option>
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">Target Languages</label>
            <div className="grid grid-cols-2 gap-2">
              {LANGUAGES.map(lang => (
                <motion.button
                  key={lang.code}
                  type="button"
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                  onClick={() => toggleLang(lang.code)}
                  className={`flex items-center gap-2 px-3 py-2 rounded-xl border text-sm transition-all ${
                    selectedLangs.includes(lang.code)
                      ? 'border-bazaar-400 bg-bazaar-500/10 text-bazaar-400 font-medium shadow-sm'
                      : 'border-[#2a2a2d] text-gray-500 hover:border-[#333]'
                  }`}
                >
                  <span>{lang.flag}</span>
                  <span>{lang.name}</span>
                  <span className="text-xs opacity-60">{lang.nameNative}</span>
                </motion.button>
              ))}
            </div>
          </div>

          <motion.button
            type="submit"
            disabled={loading}
            whileHover={{ scale: loading ? 1 : 1.01 }}
            whileTap={{ scale: loading ? 1 : 0.99 }}
            className="btn-secondary w-full flex items-center justify-center gap-2 disabled:opacity-50"
          >
            {loading ? (
              <>
                <RotateCcw className="w-4 h-4 animate-spin" />
                Generating in {selectedLangs.length} languages...
              </>
            ) : (
              <>
                <Zap className="w-4 h-4" />
                Generate Descriptions
              </>
            )}
          </motion.button>

          {error && (
            <div className="p-4 bg-amber-500/10 border border-amber-500/20 rounded-xl text-sm text-amber-400">
              AI features temporarily limited. Our servers are experiencing high demand. Please try again in a few minutes.
            </div>
          )}
        </form>

        {/* Results */}
        <div className="lg:col-span-3 space-y-4">
          <AnimatePresence mode="wait">
            {loading && (
              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="space-y-4">
                {selectedLangs.map((_, i) => (
                  <div key={i} className="bg-[#1a1a1d] rounded-2xl p-6 shadow-sm shadow-black/20 border border-[#2a2a2d]">
                    <div className="skeleton h-6 w-24 mb-3 rounded-lg" />
                    <div className="skeleton h-4 w-full mb-2 rounded-lg" />
                    <div className="skeleton h-4 w-full mb-2 rounded-lg" />
                    <div className="skeleton h-4 w-3/4 mb-4 rounded-lg" />
                    <div className="space-y-2">
                      {[1,2,3].map(j => <div key={j} className="skeleton h-4 w-5/6 rounded-lg" />)}
                    </div>
                  </div>
                ))}
              </motion.div>
            )}

            {result && !loading && (
              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4">
                {result.descriptions?.map((desc: any, i: number) => {
                  const isExpanded = expandedIdx === i
                  const fullText = `${desc.title}\n\n${desc.description}\n\n${desc.bulletPoints?.map((b: string) => `• ${b}`).join('\n')}`

                  return (
                    <motion.div
                      key={desc.language}
                      initial={{ opacity: 0, y: 15 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: i * 0.1 }}
                      whileHover={{ y: -1 }}
                      className="bg-[#1a1a1d] rounded-2xl p-5 shadow-sm shadow-black/20 border border-[#2a2a2d] hover:shadow-md transition-all overflow-hidden"
                    >
                      {/* Language Header */}
                      <div
                        className="flex items-center justify-between cursor-pointer"
                        onClick={() => setExpandedIdx(isExpanded ? null : i)}
                      >
                        <div className="flex items-center gap-3">
                          <span className="text-2xl">{LANGUAGES.find(l => l.code === desc.language)?.flag || '🌐'}</span>
                          <div>
                            <h3 className="font-semibold text-gray-100">{desc.languageName}</h3>
                            <p className="text-xs text-gray-400">{desc.language.toUpperCase()}</p>
                          </div>
                        </div>
                        <div className="flex items-center gap-2">
                          <motion.button
                            whileHover={{ scale: 1.1 }}
                            whileTap={{ scale: 0.9 }}
                            onClick={(e) => { e.stopPropagation(); shareDescriptionWhatsApp(desc) }}
                            className="p-2 hover:bg-green-500/10 rounded-lg transition-all"
                            title="Share on WhatsApp"
                          >
                            <Share2 className="w-4 h-4 text-green-500" />
                          </motion.button>
                          <motion.button
                            whileHover={{ scale: 1.1 }}
                            whileTap={{ scale: 0.9 }}
                            onClick={(e) => { e.stopPropagation(); handleCopy(fullText, i) }}
                            className="p-2 hover:bg-white/[0.06] rounded-lg transition-all"
                            title="Copy to clipboard"
                          >
                            {copiedIdx === i ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4 text-gray-400" />}
                          </motion.button>
                          {isExpanded ? <ChevronUp className="w-5 h-5 text-gray-400" /> : <ChevronDown className="w-5 h-5 text-gray-400" />}
                        </div>
                      </div>

                      <AnimatePresence>
                        {isExpanded && (
                          <motion.div
                            initial={{ height: 0, opacity: 0 }}
                            animate={{ height: 'auto', opacity: 1 }}
                            exit={{ height: 0, opacity: 0 }}
                            transition={{ duration: 0.2 }}
                          >
                            <div className="mt-4 pt-4 border-t border-[#2a2a2d]">
                              <h4 className={`text-lg font-bold text-gray-100 mb-3 ${['hi', 'mr'].includes(desc.language) ? 'font-hindi' : ''}`}>
                                {desc.title}
                              </h4>
                              <p className={`text-gray-400 leading-relaxed whitespace-pre-wrap mb-4 ${['hi', 'mr'].includes(desc.language) ? 'font-hindi' : ''}`}>
                                {desc.description}
                              </p>
                              {desc.bulletPoints?.length > 0 && (
                                <div className="mb-4">
                                  <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Key Selling Points</p>
                                  <ul className={`space-y-1 ${['hi', 'mr'].includes(desc.language) ? 'font-hindi' : ''}`}>
                                    {desc.bulletPoints.map((bp: string, j: number) => (
                                      <li key={j} className="flex items-start gap-2 text-sm text-gray-400">
                                        <span className="text-bazaar-500 mt-0.5">•</span>
                                        {bp}
                                      </li>
                                    ))}
                                  </ul>
                                </div>
                              )}
                              {desc.culturalNotes && (
                                <div className="p-3 bg-saffron-500/10 rounded-xl mb-3 border border-saffron-500/20">
                                  <p className="text-xs font-semibold text-saffron-400 uppercase tracking-wider">Cultural Adaptation</p>
                                  <p className="text-sm text-saffron-400 mt-1">{desc.culturalNotes}</p>
                                </div>
                              )}
                              {desc.localSearchTerms?.length > 0 && (
                                <div>
                                  <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2 flex items-center gap-1">
                                    <Search className="w-3 h-3" /> SEO Keywords
                                  </p>
                                  <div className="flex flex-wrap gap-1">
                                    {desc.localSearchTerms.map((kw: string, j: number) => (
                                      <motion.span
                                        key={j}
                                        initial={{ opacity: 0, scale: 0.8 }}
                                        animate={{ opacity: 1, scale: 1 }}
                                        transition={{ delay: j * 0.05 }}
                                        className="text-xs px-2 py-1 bg-white/[0.03] text-gray-400 rounded-md"
                                      >
                                        {kw}
                                      </motion.span>
                                    ))}
                                  </div>
                                </div>
                              )}
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </motion.div>
                  )
                })}
              </motion.div>
            )}

            {!result && !loading && (
              <div className="bg-[#1a1a1d] rounded-2xl shadow-sm shadow-black/20 border border-[#2a2a2d] text-center py-16 text-gray-400">
                <Languages className="w-16 h-16 mx-auto mb-4 text-gray-600" />
                <p className="text-lg font-medium">Generate multilingual product descriptions</p>
                <p className="text-sm mt-2">Click a "Quick Demo" button to try with a pre-loaded product</p>
              </div>
            )}
          </AnimatePresence>
        </div>
      </div>
      <DemoModeBadge visible={!!result?.demoMode} />
    </div>
  )
}
